name: Dispatch Web Service Update
on:
   workflow_call:
    inputs:
      type:
        type: string
        required: true
      version:
        type: string
        required: true
      repo:
        type: string
        required: true
    secrets:
      TOKEN: 
        required: true 
    # outputs: 
      # token: ${{ steps.encrypt-token.outputs.out }}
      # sha: ${{ steps.short-sha.outputs.short-sha }}
      # # Get a short sha of the commit triggering this run, will be used in the commit message in the tarrget repos
      # - name: Get Short SHA 
      #   id: short-sha
      #   run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      #   working-directory: templates
jobs:
  dispatch-web-update:
    name: Dispatch Web Service Update
    runs-on: ubuntu-latest
    outputs: 
      token: ${{ steps.encrypt-token.outputs.out }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: digi-serve/ab_service_web
          event-type: pwa_new_version
          client-payload: '{"type": "${{ inputs.type }}", "version": "${{ inputs.version }}", "repo": "${{ inputs.repo }}"}'


