name: Dispatch Web Service Update
on:
   workflow_call:
    inputs:
      type:
        type: string
        required: true
      version:
        type: string
        required: true
      repo:
        type: string
        required: true
    secrets:
      TOKEN: 
        required: true 
jobs:
  dispatch-web-update:
    name: Dispatch Web Service Update
    runs-on: ubuntu-latest
    outputs: 
      token: ${{ steps.encrypt-token.outputs.out }}
    steps:
    #   - name: Generate a token
    #     id: generate-token
    #     uses: actions/create-github-app-token@v2
    #     with:
    #       app-id: ${{ vars.GS_DEV_APP_ID }}
    #       private-key: ${{ secrets.GS_DEV_APP_PK }}
    #       owner: ${{ github.repository_owner }}
    #       skip-token-revoke: true
    #   - name: encrypt-token
    #     id: encrypt-token
    #     uses: cloudposse/github-action-secret-outputs@main
    #     with:
    #       secret: ${{ secrets.ENCRYPTION_PASSWORD }}
    #       op: encode
    #       in: 
    #         ${{ steps.generate-token.outputs.token }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: digi-serve/ab_service_web
          event-type: pwa_new_version
          client-payload: '{"type": "${{ inputs.type }}", "version": "${{ inputs.version }}", "repo": "${{ inputs.repo }}"}'


